server:
  port: 7900
  context-path: /

spring:
  mvc:
    view:
      suffix: .html
  application:
    name: cloudshopper-web
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}