server:
  port: 7902

spring:
  application:
    name: cloudshopper-tools
eureka:
  # 设置环境标识
  environment: dev
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${spring.cloud.client.ipAddress}:${server.port}}